### ISSUE TITLE
packetnet-connections calls missing method in packet.net

### ISSUE THREAD

**Issue by nutshoekey** [chmorgan/packetnet-connections#1]
When calling 
`PacketDotNet.Connections.TcpConnectionManager.ProcessPacket(PosixTimeval timeval, TcpPacket tcp)`
a missing method exception will be thrown.
Stack trace:
```
System.MissingMethodException: Method not found: 'Boolean PacketDotNet.TcpPacket.get_Rst()'.
   at PacketDotNet.Connections.TcpConnectionManager.ProcessPacket(PosixTimeval timeval, TcpPacket tcp)
```

The cause seems to be in PacketDotNetConnections/TcpConnectionManager.cs line 86
                `if(tcp.Rst)`
packet.net TcpPacket only has Reset, not Rst

My version of packet.net is 1.0.1, packet.net-connections seems to be using 0.20.1 which does not have that method
.net core 2.2.300 sdk

**Comment by chmorgan** [comment]
Hi @nutshoekey, thank you for the feedback. I'll see if I can't fix that this weekend and get a new version pushed up to GitHub for you to check out.

**Comment by chmorgan** [comment]
HI @nutshoekey, packetdotnet 1.0.1 fixes pushed to master, let me know if they don't resolve the issue for you.

**Comment by drake7707** [comment]
Can you also update the nuget package of packetnet-connections?
