### ISSUE TITLE
This is a good project

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/packetnet-connections#4]
, you can use packetnet connections + SharpPcap to monitor the specific data of all HTTP requests in the network, right? Can HTTPS also be monitored?

**Comment by chmorgan** [comment]
I know wireshark and other systems can monitor ssl connections if you have
the keys but afaik libpcap doesn’t provide this functionality. If there was
another library that did we could look to integrate it but at the moment
sharppcap doesn’t do ssl decoding.

Chris

**Comment by bbhxwl** [comment]
I see. I'm looking forward to supporting projects. Thank you. . net's open source projects are really too few. In particular, projects that support. Net core. Author, you are so hard

**Comment by chmorgan** [comment]
Appreciate that you are finding it helpful!
