### ISSUE TITLE
Nuget packetnet connections 1.0.0 is not compatible with this example

### ISSUE THREAD

**Issue by bbhxwl** [chmorgan/packetnet-connections#7]
Nuget packetnet connections 1.0.0 is not compatible with this example

![QQ图片20200720015043](https://user-images.githubusercontent.com/26525599/87881422-be19fc80-ca2b-11ea-80f2-3bad45d5e869.png)

**Comment by PikminGuts92** [comment]
Yes, the version for `packetnet-connections` is still 1.0.0 on Nuget. Can it you please update the release to include the latest changes?

**Comment by chmorgan** [comment]
@PikminGuts92 ok. I'm upgrading visual studio here but I can look at updating the version and pushing it up in the next few days.

**Comment by chmorgan** [comment]
@PikminGuts92 should be all set. @bbhxwl can you confirm it's working as expected now? If not please reopen.
